services:
  - type: web
    name: barista-api
    runtime: node
    plan: free
    region: frankfurt
    healthCheckPath: /api/health
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: barista-db
    plan: free
    region: frankfurt
    databaseName: barista
    user: barista
